# Generated by Django 3.0.8 on 2020-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200912_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='mechanical', max_length=200),
            preserve_default=False,
        ),
    ]
